version: '3.9'

services:
  archimed-frontend:
    container_name: frontend
    restart: always
    build: ./frontend/
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - 3000:3000
    environment:
      - API_ENDPOINT=http://archimed-api:8000
  archimed-api:
    container_name: api
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    restart: always
    build: ./api/
    volumes:
      - ./api/:/api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=archimed
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=archimed-postgres
      - POSTGRES_PORT=5432
      - SECRET_KEY=secret
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=password
    depends_on:
      - archimed-postgres
  archimed-postgres:
    container_name: archimed-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=archimed
